version: '2.39.43'
services:
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: tukaevar-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - tukaevar-my-netology-hw
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.11.1
    container_name: tukaevar-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - tukaevar-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: tukaevar-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - tukaevar-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped
volumes:
  prometheus-data:
  grafana-data:
networks:
  tukaevar-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
